apiVersion : apps/v1
kind: Deployment
metadata:
  name: "panda50cluster-c0c0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "panda50cluster-c0c0"
  template:
    metadata:
      labels:
        app: "panda50cluster-c0c0"
    spec:
      containers:
        - name: "panda50cluster-c0c0"
          image: "panda50registry.azurecr.io/panda50cluster"
          ports:
          - containerPort: 8080