apiVersion: v1
kind: Service
metadata:
    name: "panda50cluster-2f2d"
    labels:
        app: "panda50cluster-2f2d"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "panda50cluster-2f2d"