apiVersion: v1
kind: Service
metadata:
  name: panda50-front-service
spec:
  selector:
    app: panda50-front
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: panda50-front
spec:
  selector:
    matchLabels:
      app: panda50-front
  replicas: 2
  template:
    metadata:
      labels:
        app: panda50-front
    spec:
      containers:
      - name: panda50-front
        image: panda50registry.azurecr.io/panda50-front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acrdemo2ss-secret
