on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: panda50registry.azurecr.io
        username: ${{ secrets.acr_panda50registry_username }}
        password: ${{ secrets.acr_panda50registry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t panda50registry.azurecr.io/panda50cluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push panda50registry.azurecr.io/panda50cluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_panda50cluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep panda50clusterb55f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace panda50clusterb55f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: panda50clusterb55f
        container-registry-url: panda50registry.azurecr.io
        container-registry-username: ${{ secrets.acr_panda50registry_username }}
        container-registry-password: ${{ secrets.acr_panda50registry_password }}
        secret-name: panda50clustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: panda50clusterb55f
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          panda50registry.azurecr.io/panda50cluster:${{ github.sha }}
        imagepullsecrets: |
          panda50clustdockerauth
